# Generated by Django 5.2.4 on 2025-08-11 21:32
import django.utils.timezone
from django.db import migrations, models

def fill_unique_ubigeo_codes(apps, schema_editor):
    Country = apps.get_model('Reflexo', 'Country')
    for idx, country in enumerate(Country.objects.all(), start=1):
        country.ubigeo_code = f"UBG{idx:04d}"  # Genera UBG0001, UBG0002, etc.
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('Reflexo', '0005_alter_country_options_alter_district_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='ISO2',
        ),
        migrations.RemoveField(
            model_name='country',
            name='phone_code',
        ),
        # 1️⃣ Agregar el campo sin unique y permitiendo null
        migrations.AddField(
            model_name='country',
            name='ubigeo_code',
            field=models.CharField(max_length=10, null=True, blank=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='country',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        # 2️⃣ Rellenar con valores únicos
        migrations.RunPython(fill_unique_ubigeo_codes),
        # 3️⃣ Modificar el campo para hacerlo único y no nulo
        migrations.AlterField(
            model_name='country',
            name='ubigeo_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]