# Generated by Django 5.2.4 on 2025-08-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reflexo', '0006_remove_country_iso2_remove_country_phone_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='ubigeo_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
