[pytest]
DJANGO_SETTINGS_MODULE = Config.settings
python_files = tests.py test_*.py *_tests.py
addopts = 
    --strict-markers
    --strict-config
    --tb=short
testpaths = Reflexo/test
markers =
    slow: marks tests as slow (deselect with '-m "not slow"')
    integration: marks tests as integration tests
