# .github/workflows/django.yml
name: Django CI

on:
  push:
    branches: [main, develop, ESTRUCTURA-DJANGO, proyect-web, Distritos]
  pull_request:
    branches: [main, develop, Proyect-web]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DJANGO_SETTINGS_MODULE: Config.settings
      PYTHONPATH: ${{ github.workspace }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django check
      run: |
        python manage.py check

    - name: Run Django migrations
      run: |
        python manage.py makemigrations --check --dry-run
        python manage.py migrate

    - name: Run tests with pytest
      run: |
        pytest

    - name: Run Django collectstatic (dry run)
      run: |
        python manage.py collectstatic --dry-run --noinput

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
